name: Lint using Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store all python files in env variable
        run: |
            echo "py_files=$(find . -name '*.py' | tr '\n' ' ')" >> $GITHUB_ENV
      - uses: psf/black@stable
        with:
            options: "--verbose"
            src: "${{ env.py_files }}"
            version: "21.5b1"
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xo pipefail
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch
          git add .
          git commit -m "Lint $(git rev-parse source | grep -o '^.\{10\}')"
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" ${{ github.ref }}