name: Lint using Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store all python files in env variable
        run: |
            echo "py_files=$(find . -name '*.py' | tr '\n' ' ')" >> $GITHUB_ENV
      - uses: psf/black@stable
        id: lintcheck
        with:
          options: "--verbose"
          src: "${{ env.py_files }}"
          version: "21.5b1"

      - uses: psf/black@stable
        if: steps.lintcheck.outcome != 'success'
        with:
            options: "--verbose"
            src: "${{ env.py_files }}"
            version: "21.5b1"

      - name: Commit changes
        if: steps.lintcheck.outcome != 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xo pipefail
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch
          git add .
          git commit -m "Lint $(git rev-parse ${{ github.ref }} | grep -o '^.\{10\}')"
          git push
